### ISSUE TITLE
BFGS trouble with large system

### ISSUE THREAD

**Issue by yuap94** [gmx2qmmm/gmx2qmmm_portable#4]
Memory problems with large system ->Try [Limited-memory_BFGS](https://en.wikipedia.org/wiki/Limited-memory_BFGS)

**Comment by yuap94** [comment]
Reference : [A limited memory BFGS-type method for large-scale unconstrained optimization](https://www.sciencedirect.com/science/article/pii/S0898122108001028)

**Comment by AlinaJansen** [comment]
Problem fixed, but not implemented in branch of version 2 yet.
