### ISSUE TITLE
transparency of the optimization

### ISSUE THREAD

**Issue by spetrypy** [gmx2qmmm/gmx2qmmm_portable#8]
The actual version of gmx2qmmm is missing the information of all steps of a optimization. There should be at least the possibility to save them during the optimization and store them as a compressed folder. 
Is not this information necessary for restarting/continue a calculation at a certain checkpoint ?

**Comment by yuap94** [comment]
In qmmm file, _optlastonly_ is the parameter that determines to keep steps files or not. In the latest version in branch p3, the compressed tar file function is added.

if _optlastonly = yes_, the output will only remain the last information of optimization, which is the default setting.
if _optlastonly = no_, the output will remain all steps of optimization. Besides the last step, all information will be archived as tar files.

**Comment by yuap94** [comment]
The _optlastonly_ in qmmm parameter was changed to _print_level_, a better name for parameter.
if  _print_level_ = normal, the output will only remain the last information of optimization, which is the default setting.
if  _print_level_ = full, the output will remain all steps of optimization. Besides the last step, all information will be archived as tar files.
Please see the details in https://gmx2qmmm.github.io/gmx2qmmm_io/input_params/input_params
