### ISSUE TITLE
P3-branch

### ISSUE THREAD

**Issue by spetrypy** [gmx2qmmm/gmx2qmmm_portable#9]
If you use the a gro-file as a input, the write_highprec function is missing (readInput.py). 

Furthermore, the gmx2qmmm/pointcharges/generate_pcf_from_top.py has a small error at line 246 and missing the inp information: 
"file = open("conf.gro", "r")"

**Comment by yuap94** [comment]
Thanks!
write_highprec function is added & gmx2qmmm/pointcharges/generate_pcf_from_top.py  is fixed
